<?php
include_once"settings/settings.php";
include_once"classes/userclass.php";
$obj=new userclass();
session_start();
if(isset($_COOKIE['logined'])&&$_COOKIE['logined']==1)
{
$key=$_COOKIE['lkey'];
//$akey=$_GET['akey'];
$e=$obj->addtocartview($key);
$smartyObj->assign("data",$e);
$h=$obj->addtocartview1($key);
$smartyObj->assign("amount",$h);
$smartyObj->display("memberssubheader.tpl");
$smartyObj->display("addtocartview.tpl");
$smartyObj->display("footer.tpl");
}
else
{
	header("location:login.php");
}	
?>