<?php
include_once"settings/settings.php";
include_once"classes/userclass.php";
$obj=new userclass();
session_start();
if(isset($_COOKIE['logined'])&&$_COOKIE['logined']==1)
{
$key=$_COOKIE['lkey'];
$e=$obj->adminfbview($key);
$smartyObj->assign("view",$e);
$smartyObj->display("adminsubheader.tpl");
$smartyObj->display("feedbackview.tpl");
$smartyObj->display("adminfooter.tpl");
}
else
{
	header("location:login.php");
}	
?>