<?php
include_once"settings/settings.php";
include_once"classes/userclass.php";
$obj=new userclass();
$key=$_COOKIE['lkey'];
session_start();
if(isset($_COOKIE['logined'])&&$_COOKIE['logined']==1)
{
$e=$obj->krowview($key);
$smartyObj->assign("data",$e);
$smartyObj->display("kudumbasreesubheader.tpl");
$smartyObj->display("kviewrow.tpl");
$smartyObj->display("footer.tpl");
}
else
{
	header("location:login.php");
}	
?>